title: Ben Ramey's Blog
tagline: "Programming problems, solutions and stories"
description: I'm a .NET programmer working for VML.

markdown: redcarpet
highlighter: rouge

paginate: 5
baseurl: /
searchbaseurl: 'http://www.benramey.com'
url: 'http://www.benramey.com'

google_analytics_id: 'UA-1380501-7'
disqus: true
disqus_shortname: 'fishybusiness'

author:
    name: 'Ben Ramey'
    url: 'http://www.benramey.com'

permalink:       /:year/:month/:day/:title/
