title: Ben Ramey's Blog
tagline: "Programming problems, solutions and stories"
description: I'm a .NET programmer working for VMLY&R.

markdown: kramdown
highlighter: rouge

url: 'https://www.benramey.com'

google_analytics_id: 'UA-1380501-7'
disqus: true
disqus_shortname: 'fishybusiness'

author:
    name: 'Ben Ramey'
    url: 'https://www.benramey.com'

permalink: /:year/:month/:day/:title/
