# Setup
title: Ben Ramey's Blog
tagline: "Scripture, programming problems, solutions and stories."
url: 'https://www.benramey.com'
paginate: 1
baseurl: ""
permalink: /:year/:month/:day/:title/

author:
    name: 'Ben Ramey'
    url: 'https://www.benramey.com'
    email: benramey@fastmail.com

plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-seo-tag

exclude:
    - .editorconfig
    - .git
    - .jekyll-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
    - node_modules
    - src
    - package.json
    - package-lock.json
    - webpack.config.js

include:
    - assets

markdown: kramdown
highlighter: rouge

# custom
google_analytics_id: 'UA-1380501-7'
disqus: true
