title: Ben Ramey's Blog
tagline: "Programming problems, solutions and stories"
description: I'm a .NET programmer working for VML.

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
url: 'http://www.benramey.com'

google_analytics: 'UA-1380501-7'
disqus: true
disqus_shortname: 'fishybusiness'

author:
    name: 'Ben Ramey'
    url: 'http://www.benramey.com'

permalink:       /:year/:month/:day/:title/